title: Pattern Library
description: A collection of patterns to help you build up a style guide for your site

destination: ./_site
plugins:     _plugins
layouts:     _layouts
includes:    _includes
include:     ['.htaccess']
exclude:
  - _config.yaml
  - example.info
  - Gemfile
  - Gemfile.lock
  - README.md
keep_files:  ['.git']
timezone:    Europe/London
markdown:    redcarpet
permalink:   /:title
highlighter: pygments

availability: "November 2015"

paginate: 20
paginate_path: "/archives/page/:num"

collections:
  patterns:
    output: true
    title: Patterns
  talks:
    output: true
    title: Talks
  projects:
    output: true
    title: Projects
    permalink: /projects/:path/
  portfolio:
    output: true
    title: Portfolio
    permalink: /portfolio/:path/
  podcasts:
    output: true
    title: Podcasts
  articles:
    output: true
    title: Articles
